# site settings

title: Nabin from Nepal
description: a tech enthusiast, web developer
taglong: a tech enthusiast, web developer
tagshort: Jekyll magic
url: https://bhattnabin.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/bhattnabin/bhattnabin.github.io

# author settings

author:
  name: nabin
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: nabinbhatt
  twitter: thenabinbhatt

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
